### PR TITLE
parsing provenance

### PR DESCRIPTION
**Pull request by petrelharp**
This might be useful to you, @mufernando - could you have a look and see if it does things you'd want to do?

### CODE REVIEW

**Comment by mufernando** [comment]
It would be good to return the SLiM command and seed.

**Comment by petrelharp** [comment]
> It would be good to return the SLiM command and seed.

Ah, so add these to the `pyslim.Provenance` structure?  Or maybe just include the whole parsed provenance dictionary, really?

**Comment by mufernando** [comment]
With your  second option do you mean parsing all the different fields in the JSON and including them all?

I think most users wouldn't need more than the seed and the SLiM command, but don't see a huge downside to parsing the whole thing.

Let me know and I can help implementing either of these.

**Comment by petrelharp** [comment]
Ok, let's see. Right now, we can get information by parsing the provenance entry with `json` directly:
```
prov = json.loads(ts.provenance(0).record)
for k in prov:
  if isinstance(prov[k], dict):
    print(k, ":")
    for kk in prov[k]:
        print("   ", kk, prov[k][kk])
  else:
    print(k, prov[k])
```
which gets
```
environment :
    os {'machine': 'x86_64', 'node': 'skua', 'release': '4.19.0-2-amd64', 'system': 'Linux', 'version': '#1 SMP Debian 4.19.16-1 (2019-01-17)'}
metadata :
    individuals {'flags': {'16': {'description': 'the individual was alive at the time the file was written', 'name': 'SLIM_TSK_INDIVIDUAL_ALIVE'}, '17': {'description': 'the individual was requested by the user to be remembered', 'name': 'SLIM_TSK_INDIVIDUAL_REMEMBERED'}, '18': {'description': 'the individual was in the first generation of a new population', 'name': 'SLIM_TSK_INDIVIDUAL_FIRST_GEN'}}}
parameters :
    command ['slim', 'recipe_WF.slim']
    model initialize()
{
    setSeed(23);
    initializeTreeSeq();
    initializeMutationRate(1e-2);
    initializeMutationType("m1", 0.5, "f", -0.1);
    initializeGenomicElementType("g1", m1, 1.0);
    initializeGenomicElement(g1, 0, 99);
    initializeRecombinationRate(1e-2);
}

1 { 
    sim.addSubpop("p1", 10);
}

10 {
    sim.treeSeqOutput("recipe_WF.trees");
    catn("Done.");
    sim.simulationFinished();
}

    model_hash c97711cae1feb5f86fe9d948c34167bbdae1d8fe895a2a14da517a24425a9f04
    model_type WF
    seed 1711090956800
schema_version 1.0.0
slim :
    file_version 0.4
    generation 10
software :
    name SLiM
    version 3.3.2
```

And, from the pre-parsed information:
```
ts.slim_provenance
# ProvenanceMetadata(model_type='WF', slim_generation=10, file_version='0.4')
```
I don't think we want to parse *everything* here - for instance, one of the entries is `metadata`, which tells us what the individual flags that SLiM is using mean; that's internal to pyslim. I was suggesting adding another slot, say `record` to the `ProvenanceMetadata` class, that has the dictionary returned by `json.loads(ts.provenance(j).record)` in it (ie the first thing).  Then one could get `seed` by doing
```
ts.slim_provenance.record['parameters']['seed']
```

This would make everything accessible, which is good - although it is already accessible with just a `json.loads( )`. If there's just a few things that are obviously and often useful then we should add them as properties of the provenance metadata itself. I'm not sure if `seed` is one of those things, since it seems like we should put things in the `ProvenanceMetadata` class things that we might want to use within pyslim itself?  Thoughts?

**Comment by mufernando** [comment]
Yes, I think just dumping the whole record onto the `ProvenanceMetadata` class is the best thing. And then people can parse it to their liking.

**Comment by petrelharp** [comment]
I'm going to merge this and we can extend the provenance metadata separately.

**Pull request merged**
