### PR TITLE
Use only public tskit API

### PR DESCRIPTION
**Pull request by benjeffery**
Here's a quick sketch of how it could work without subclassing `tskit.TreeSequence`. There's a bit more boilerplate, so it is a trade-off.

### CODE REVIEW

**Comment by petrelharp** [comment]
Ah, I see! Hm, thanks. It's not too much more boilerplate. What do you think? Is this a better way to do things?

**Comment by petrelharp** [comment]
Hm, to use only the public API I'll need to figure out a way around this, too: https://github.com/tskit-dev/pyslim/blob/update_tskit/pyslim/slim_tree_sequence.py#L380

**Comment by petrelharp** [comment]
Gee, this has the downside that tab completion no longer works. But it seems to be solving some other problems, so...

**Comment by petrelharp** [comment]
Hmph, another annoyance is that `isinstance(ts, tskit.TreeSequence)` is no longer true.

**Comment by petrelharp** [comment]
And, `@property` appears to not work either.

(Apologies for my stream-of-consciousness notes here...)

**Comment by jeromekelleher** [comment]
I was wondering if the SlimTreeSequence class is actually needed at all now - other than the ``recaptitate`` method, it's not really doing much that tskit isn't now, right?

The ``recapitate`` method could be made a function instead and monkey-patched in to the TreeSequence object for backwards compatibility.

**Comment by petrelharp** [comment]
That's true - but, it does have a few extra properties: `.slim_generation` and `.reference_sequence` (sometimes). Although the first is really part of top-level metadata now.

I've pulled these commits into #95, btw.

**Comment by benjeffery** [comment]
I'll close this PR if you've used the commits in #95. Thanks!

**Comment by petrelharp** [comment]
Gah, there's a significant problem with this approach: anywhere that code uses `isinstance(ts, TreeSequence)` will fail. In the msprime code this happens [here](https://github.com/tskit-dev/msprime/blob/master/msprime/ancestry.py#L314) and [here](https://github.com/tskit-dev/msprime/blob/master/msprime/provenance.py#L128). The second one (provenance construction) means I need to provide an `asdict` method so that, for instance, `msprime.mutate( )` will work on a SlimTreeSequence. I'm not sure how to get around the first one. But this is seeming fragile.

**Pull request closed without merging**
