### PR TITLE
deal with `first` stage

### LINKED ISSUE #170: deal with `first()` stages
In 3.7 there will be a `first()` stage. See https://pyslim.readthedocs.io/en/latest/metadata.html#converting-from-slim-time-to-tskit-time for discussion.

### PR DESCRIPTION
**Pull request by petrelharp**
This closes #170, and is stacked on #275.

### CODE REVIEW

**Comment by petrelharp** [comment]
Well, that was painful!

**Comment by bhaller** [comment]
Out of curiosity, why was it so painful?

**Comment by petrelharp** [comment]
It was painful because the right answers to "what SLiM time was this tskit time?" and "what age was this indvidual at this SLiM time?" depends on (a) the stage at which individuals were Remembered, (b) the stage at which the ts was written out, (c) the stage we're asking about the time of, and (d) whether its WF or nonWF. That's 54 different combinations. Have a look at [these two tables](https://tskit.dev/pyslim/docs/latest/metadata.html#converting-from-slim-time-to-tskit-time) which don't even get into discussing ages, which have a few more wrinkles.

> The sha of the head commit of this PR conflicts with https://github.com/tskit-dev/pyslim/pull/275.

That message is because I started this PR on top of the commits from that other PR, and dissappeared once I merged the other PR. Mergify is a service that helps you do automatic merging of PRs and things like that; I'm not using it anyhow.

**Comment by bhaller** [comment]
54 different combinations, yeesh.  I guess this was my revenge for the "remapping population table indices" thing.  ;->

Re: the message, so basically two PRs both referenced the same SHA, because one was based upon the other, and mergify bot doesn't like that?  OK, I think I see.

**Pull request merged**
