### PR TITLE
switch over to msprime 1.0 API

### PR DESCRIPTION
**Pull request by petrelharp**
Here's a start at that.

To view these docs, you can
```
git fetch origin pull/101/head:msprime_v1
git checkout msprime_v1
cd docs
make
```
and then direct a web browser to the `docs/_build/html` directory.

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Should we be using ``sim_ancestry`` rather than ``simulate``?

**Comment by petrelharp** [comment]
> Should we be using sim_ancestry rather than simulate?

Yes! I'm just waiting 'til the new API has settled down to switch everything over. (has it settled, then?)

**Comment by jeromekelleher** [comment]
> Yes! I'm just waiting 'til the new API has settled down to switch everything over. (has it settled, then?)

No, but soon. Next job after I land this big tables refactoring.

**Comment by petrelharp** [comment]
Mostly superceded by #154.

**Pull request closed without merging**
