### PR TITLE
Add decoded metadata to objects (and individual time, population)

### PR DESCRIPTION
**Pull request by petrelharp**
Individuals carry a list of nodes, and nodes have `time` and `population` for historical reasons. Here I've propagated these properties to the `individual`, and throw an error if they don't all agree.  Anything else along these lines we should propagate?  Are there any use cases where we expect more than one time or population?

### CODE REVIEW

**Comment by petrelharp** [comment]
It could also be nice to provide methods that returns a numpy array of the things in metadata, e.g., ages, population, [location](#28), etc? This can be seen [here](https://github.com/gbradburd/spgr/blob/f4b175a8c51ecedf6196b682e417f60df53b058c/plots/spatial_slim/spatial_slim_ts.py#L268).

**Comment by petrelharp** [comment]
I've added a number of useful things here:

1. Individual objects now have properties that we extract from the metadata.
2. SlimTreeSequences have attributes that are numpy arrays like `ts.individual_ages` and `ts.individual_sex` that act like columns in the individual table.
3. There's methods to ask "who was alive at this time?" and "how old were they at this time?"

The first thing we can copy to allow easier access to metadata for mutations, etcetera.

**Comment by petrelharp** [comment]
At first I tended towards making *all* the properties of metadata also properties of the individual, directly, so you could just type `ind.sex` instead of `ind.metadata.sex`. However, this got awkward for mutations, which have a *list* of metadata objects (thanks to mutation stacking).  So, I've implemented so far `ind.metadata` and `mut.metdata`, e.g.:
```
for ind in ts.individuals():
  print(ind.metadata)
```
Note that these can't be modified (or if they are it won't go back to the tree sequence).

**Comment by petrelharp** [comment]
I would like to merge this; if anyone (@hyanwong? @bhaller? @cjbattey? @jgallowa07? @jeromekelleher? @gtsambos?) has any input on the API, lmk soon.

**Comment by bhaller** [comment]
This sounds reasonable to me, to the extent I understand what's going on in Python.  :->  The "can't be modified" caveat should of course be documented carefully.

**Comment by petrelharp** [comment]
Agreed. I really ought to write some more better documentation...

**Pull request merged**
